### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheSnottyMidget** [mhwlng/streamdeck-starcitizen#2]
Hi, thank you for creating this plug, it is awesome!

I was wondering if I could submit a feature request for it, to have a second button, that is a toggle button, similar to how the stream deck "Hotkey Switch" works with two functions, and icon swapping for on off toggles, like vehicle power, shields, weapons on/off etc.

Thank you for your time, and creating such an awesome plugin!

**Comment by mhwlng** [comment]
---

**Comment by mhwlng** [comment]
sorry, I gave the wrong answer (it was about the elite dangerous plugin)

the game doesn't return any kind of game state, 
So I can't make toggle buttons (like for the elite dangerous plugin)
because when you press the button at the wrong moment, then it shows the wrong on/off button image.

You can make it yourself using the multi-action switch built into the streamdeck
